name: Optimize resource pack

on:
  workflow_dispatch:
  push:
    branches: main

permissions:
  contents: write

jobs:
  packsquash_32x:
    name: Optimize 32x resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run PackSquash 32x
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest-unstable
          artifact_name: 'Conquest32'
          options: |
            pack_directory = '.'
            output_file_path = '/tmp/Conquest32.zip'
            allow_mods = ['OptiFine', 'Minecraft Transit Railway 3']
            zip_spec_conformance_level = 'high'
            spooling_buffers_size = 512
            threads = 16
            zip_compression_iterations = 20
            ['**/*?.ogg']
            ogg_obfuscation = true
            ['**/*?.png']
            image_data_compression_iterations = 40

  packsquash_16x:
    name: Optimize 16x resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Downscale to 16x
        run: |
          find assets/minecraft/textures -type f -name '*.png' -exec mogrify -resize 50% {} \;
      - name: Run PackSquash 16x
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest-unstable
          artifact_name: 'Conquest16'
          options: |
            pack_directory = '.'
            output_file_path = '/tmp/Conquest16.zip'
            allow_mods = ['OptiFine', 'Minecraft Transit Railway 3']
            zip_spec_conformance_level = 'high'
            spooling_buffers_size = 512
            threads = 16
            zip_compression_iterations = 20
            ['**/*?.ogg']
            ogg_obfuscation = true
            ['**/*?.png']
            image_data_compression_iterations = 40

  finalize-release:
    needs: [packsquash_32x, packsquash_16x]
    runs-on: ubuntu-latest
    steps:
      - name: Download 32x artifact
        uses: actions/download-artifact@v4
        with:
          name: Conquest32
          path: /tmp
      - name: Download 16x artifact
        uses: actions/download-artifact@v4
        with:
          name: Conquest16
          path: /tmp
      - name: Get Release Sizes
        id: get_sizes
        run: |
          size32=$(du -m /tmp/Conquest32.zip | cut -f1)
          size16=$(du -m /tmp/Conquest16.zip | cut -f1)
          echo "size32=$size32 MB" >> $GITHUB_ENV
          echo "size16=$size16 MB" >> $GITHUB_ENV
      - name: Create Release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: /tmp/Conquest32.zip,/tmp/Conquest16.zip
          draft: false
          prerelease: false
          release_name: ${{ github.event.head_commit.message }}

  send-webhook:
    needs: finalize-release
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-title: New Release 🔔
          embed-url: https://github.com/${{ github.repository }}
          embed-color: 3535423
          embed-description: |
            ### Commit ⚡
            Message » `${{ github.event.head_commit.message }}`
            Commit SHA » `${{ github.sha }}`
            Commit Author » `${{ github.event.head_commit.author.name }}`
            ### Workflow ☢️
            Runner OS » `${{ runner.os }}`
            Branch » `${{ env.branch }}`
            ### Release 📦
            Download » [Click here to download 32x⏬](https://github.com/${{ github.repository }}/releases/latest/download/Conquest32.zip)
            Size » `${{ env.size32 }}`
            Download » [Click here to download 16x⏬](https://github.com/${{ github.repository }}/releases/latest/download/Conquest16.zip)
            Size » `${{ env.size16 }}`
            Version » `1.21.1`
