name: Optimize resource pack
on:
  workflow_dispatch:
# This permissions section explicitly gives the workflow permission to create releases.
# Most of the time it's not needed to set it, as the default GITHUB_TOKEN permissions
# are permissive enough, but that's not always the case
permissions:
  contents: write
jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest-unstable
          options: |
            pack_directory = '.'
            output_file_path = '/tmp/Conquest.zip'
            allow_mods = ['OptiFine', 'Minecraft Transit Railway 3']    # Optifine and Custom Models
            #zip_spec_conformance_level = 'disregard'
            zip_spec_conformance_level = 'high'                         # Changed to 'high' because 'disregard' broke it
            spooling_buffers_size = 512                                 # Mb
            threads = 16                                                # I don't know the CPU Cores 😓

            zip_compression_iterations = 20                             # Max clamped value
            skip_pack_icon = true                                       # ...

            ['**/*?.ogg']
            ogg_obfuscation = true

            ['**/*?.png']
            image_data_compression_iterations = 40
      - name: Tag and create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: action-v${{ github.run_number }}
          files: /tmp/Conquest.zip
  send-webhook:
    needs: [packsquash]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Release Size
        id: get_size
        run: |
          curl -L -o release.zip https://github.com/${{ github.repository }}/releases/latest/download/Conquest.zip
          size=$(du -m release.zip | cut -f1)
          echo "size=$size MB" >> $GITHUB_ENV
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-title: New Release 🔔
          embed-url: https://github.com/${{ github.repository }}
          embed-color: 3535423
          embed-description: |
            ### Commit ⚡
            Message » `${{ github.event.head_commit.message }}`
            Commit SHA » `${{ github.sha }}`
            Commit Author » `${{ github.event.head_commit.author.name }}`
            ### Workflow ☢️
            Runner OS » `${{ runner.os }}`
            Branch » `${{ env.branch }}`
            ### Release 📦
            Download » [Click here to download ⏬](https://github.com/${{ github.repository }}/releases/latest/download/Conquest.zip)
            Size » `${{ env.size }}`
            Version » `1.21.1`
