name: Optimize resource pack
on:
  workflow_dispatch:
  pull_request:
# This permissions section explicitly gives the workflow permission to create releases.
# Most of the time it's not needed to set it, as the default GITHUB_TOKEN permissions
# are permissive enough, but that's not always the case
permissions:
  contents: write
jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest-unstable
          options: |
            pack_directory = '.'
            output_file_path = '/tmp/Conquest.zip'
            allow_mods = ['OptiFine', 'Minecraft Transit Railway 3']    # Optifine and Custom Models
            #zip_spec_conformance_level = 'disregard'
            zip_spec_conformance_level = 'high'                         # Changed to 'high' because 'disregard' broke it
            spooling_buffers_size = 512                                 # Mb
            threads = 16                                                # I don't know the CPU Cores 😓

            zip_compression_iterations = 20                             # Max clamped value
            skip_pack_icon = true                                       # ...

            ['**/*?.ogg']
            ogg_obfuscation = true

            ['**/*?.png']
            image_data_compression_iterations = 40
      - name: Tag and create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: action-v${{ github.run_number }}
          files: /tmp/Conquest.zip
