name: Code Check

on:
  pull_request:

permissions:
  contents: write

jobs:
  ollama_review:
    runs-on: ubuntu-latest
    name: 🦙 Ollama Code Review Job
    steps:
      - name: 📂 Clone repository
        uses: actions/checkout@v2

      - name: 🦙 Ollama Code Review
        uses: zakerby/gh-code-review@v0.0.2
        with:
          llm-model: 'codegemma'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
