name: 🔍 Code Check

on:
  pull_request:

permissions:
  contents: write

jobs:
  ollama_review:
    runs-on: ubuntu-latest
    name: 🦙 Ollama Code Review Job
    steps:
      - name: ⬇️ Checkout Pull Request
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: ⬇️ Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | bash
          ollama
          ollama pull codegemma

      - name: 🔍 Review Changed Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "" > Review.txt
          for file in $(git diff --name-only origin/main); do
            if [ -f "$file" ]; then
              prompt="Review the following code: $(cat $file)"
              modified_file_review=$(curl http://127.0.0.1:11434/api/generate -d '{"model": "codegemma", "prompt": "$prompt", "stream": false}' | jq -r '.response')
              Comment="Ollama Code Review for \`$file\`: $modified_file_review"
              echo "$Comment" >> Review.txt
              echo "$Comment"
            else
              echo "File $file does not exist."
            fi
          done
        shell: bash
