pack_directory = '.'
output_file_path = 'Conquest.zip'
allow_mods = ['OptiFine', 'Minecraft Transit Railway 3']
zip_spec_conformance_level = 'disregard'
size_increasing_zip_obfuscation = true
percentage_of_zip_structures_tuned_for_obfuscation_discretion = 50
spooling_buffers_size = 2048
threads = 12
zip_compression_iterations = 40
['**/*?.ogg']
ogg_obfuscation = true
['**/*?.png']
color_quantization_target = 'auto'
image_data_compression_iterations = 128
maximum_width_and_height = 8192
['README.md']
force_include = true
['LICENSE']
force_include = true
['How to install.md']
force_include = true
['overlay_*/**/*']
force_include = true
['**/*?.{fsh,vsh,glsl}']
shader_source_transformation_strategy = 'keep_as_is'
['**/space/**/*']
force_include = true